// components/Description.js
"use client";
import styles from "./Description.module.css";

export default function Description() {
  return (
    <div className={styles.wrapper}>
      <div className={styles.header}>About the Stream</div>
      <div className={styles.content}>
        ForeverFM is a 24/7 AI-powered podcast that blends news, tech, and culture. Tune in for continuous content generated by large language models and curated personalities.
      </div>
      <p className="" style={{color: "gray",fontSize: ".5rem",marginLeft: "35%",opacity: 0.3}}>Bigfoot Was Here</p>
    </div>
  );
}
